# -*- coding: utf-8 -*-
"""
GoGettr — Master content plan. 56 daily themes (8 weeks), each adapted to
7 outlets by build.py. Voice: short declaratives, second person, a number
where a number will do. No hype, no emoji. Ideas draw on the Content Vault
(Vol. 01) and original systems, spread across every pillar.

Each theme: id, pillar, series (eyebrow), hook (S1 contract), sub, beats
(S2-S6 payoff), quote (most-saveable line), numeral/label (optional stat),
keyword (Pinterest search intent), cta, accent, kind, tags.
"""

# Hashtag pools — deliberately BROAD, high-traffic tags (not niche), assembled
# per platform in build.py and capped to each platform's 2025/26 limit.
# (Pinterest uses keywords + boards instead of hashtags.)
HASHTAGS = {
    "core":     ["#selfimprovement", "#motivation", "#discipline", "#success", "#mindset", "#personalgrowth"],
    "systems":  ["#productivity", "#habits", "#discipline", "#selfimprovement", "#success"],
    "money":    ["#money", "#personalfinance", "#finance", "#wealth", "#investing", "#financialfreedom"],
    "career":   ["#career", "#success", "#entrepreneur", "#motivation", "#growth"],
    "training": ["#fitness", "#health", "#motivation", "#gym", "#discipline"],
    "recovery": ["#health", "#wellness", "#selfcare", "#mindset", "#motivation"],
    "mindset":  ["#mindset", "#motivation", "#discipline", "#success", "#growthmindset"],
    "time":     ["#productivity", "#timemanagement", "#focus", "#success", "#habits"],
    "social":   ["#confidence", "#communication", "#success", "#relationships", "#motivation"],
    "declutter":["#minimalism", "#organization", "#productivity", "#declutter", "#intentionalliving"],
    "challenge":["#discipline", "#motivation", "#selfimprovement", "#habits", "#goals"],
}

# accent + kind are hints; build.py rotates styles deterministically for grid variety.
THEMES = [
 # ---- WEEK 1 — the machine over the mood -----------------------------------
 dict(id="T01", pillar="SYSTEM DESIGN", series="SYSTEM DESIGN",
   hook="You do not need more motivation. You need fewer decisions.",
   sub="Willpower is a tax you pay every morning. A system pays it once.",
   beats=["Same wake window, every day.", "Automatic transfers on payday.",
          "Training clothes staged before bed.", "Tomorrow planned before today ends.",
          "Remove the daily negotiation."],
   quote="Remove the daily negotiation.", keyword="SYSTEMS THAT BEAT WILLPOWER",
   cta="Pick one decision to automate this week.", accent="volt", kind="list",
   tags=["systems","mindset"]),
 dict(id="T02", pillar="168 HOURS", series="THE 6PM RULE",
   hook="Your 9 to 5 pays today. What does 6 to 10 build?",
   sub="Four hours a night, repeated, becomes a direction.",
   beats=["6-7: come down.", "7-8: train.", "8-9: build one skill or asset.",
          "9-10: set tomorrow up.", "Four hours repeated becomes a direction."],
   quote="Four hours repeated becomes a direction.", keyword="EVENING ROUTINE FOR AMBITIOUS PEOPLE",
   cta="Block one 6-10 window tonight.", accent="violet", kind="sequence",
   tags=["time","systems"]),
 dict(id="T03", pillar="THE AUDIT", series="FUTURE AUDIT",
   hook="If nothing changes for 365 days, are you okay with the result?",
   sub="Answer honestly. Your lowest answer is your next project.",
   beats=["Same income?", "Same body?", "Same habits?", "Same people around you?",
          "Your lowest answer is the next project."],
   quote="Your lowest answer is your next project.", keyword="LIFE AUDIT CHECKLIST",
   cta="Name your lowest answer in the comments.", accent="volt", kind="list",
   tags=["mindset","systems"]),
 dict(id="T04", pillar="ESCAPE VELOCITY", series="MONEY MILESTONE",
   hook="Your first $10K changes the game — and not the way you think.",
   sub="The number matters. The identity shift matters more.",
   beats=["First real breathing room.", "First proof you can keep money.",
          "First time a problem does not become a crisis.", "First taste of optionality.",
          "The identity shift outlasts the balance."],
   quote="The first $10K buys something $100K cannot recreate.",
   numeral="$10K", numeral_label="buys breathing room money cannot re-create.",
   keyword="HOW TO SAVE YOUR FIRST 10K", cta="Set the target. Automate the first transfer.",
   accent="violet", kind="stat", tags=["money","mindset"]),
 dict(id="T05", pillar="RECEIPTS", series="WAKE-UP SEQUENCE",
   hook="At some point the handoff never comes. The first move is yours.",
   sub="Responsibility is where leverage starts.",
   beats=["No one builds your savings.", "No one protects your calendar.",
          "No one trains your body for you.", "No one creates your next option.",
          "Responsibility is where leverage starts."],
   quote="Responsibility is where leverage starts.", keyword="TAKE OWNERSHIP OF YOUR LIFE",
   cta="Claim one thing no one is coming to fix.", accent="volt", kind="sequence",
   tags=["mindset","core"]),
 dict(id="T06", pillar="ENVIRONMENT ENGINEERING", series="THE SUNDAY SETUP",
   hook="Want Monday to feel less expensive? Pay for it on Sunday.",
   sub="Make Monday start before Monday.",
   beats=["Read the week's calendar.", "Choose three outcomes.", "Reset your room.",
          "Stage food, clothes and chargers.", "Make Monday start before Monday."],
   quote="Make Monday start before Monday.", keyword="SUNDAY RESET ROUTINE",
   cta="Run this before you sleep tonight.", accent="violet", kind="list",
   tags=["systems","declutter"]),
 dict(id="T07", pillar="PURCHASE LAB", series="STATUS FILTER",
   hook="Would you still want it if nobody could ever see it?",
   sub="Separate preference from performance.",
   beats=["Remove the audience.", "Remove the logo.", "Remove the launch-day hype.",
          "Remove your friends seeing it.", "Still want it?"],
   quote="Separate preference from performance.", keyword="STOP IMPULSE SPENDING",
   cta="Run this before your next checkout.", accent="volt", kind="list",
   tags=["money","mindset"]),
 # ---- WEEK 2 — audits + capacity -------------------------------------------
 dict(id="T08", pillar="THE AUDIT", series="THE 7-DAY TIME LEAK AUDIT",
   hook="Your week is leaking. Find the hole before you add another goal.",
   sub="For seven days, mark every block that was neither work nor recovery.",
   beats=["Mark every non-work, non-recovery block.", "Circle anything you did by default.",
          "Add the minutes.", "Pick the biggest leak.", "Next week, block it before it starts."],
   quote="Find the leak before you add another goal.", keyword="TIME MANAGEMENT AUDIT",
   cta="Start the seven-day count today.", accent="violet", kind="sequence",
   tags=["time","systems"]),
 dict(id="T09", pillar="MONEY SYSTEMS", series="PRIORITY LADDER",
   hook="Own these before you own the flex.",
   sub="Foundation before decoration.",
   beats=["Emergency cash.", "Reliable tools for work.", "A sleep setup that works.",
          "Basic home and car readiness.", "Foundation before decoration."],
   quote="Foundation before decoration.", keyword="FINANCIAL PRIORITIES IN ORDER",
   cta="Check which rung you actually own.", accent="volt", kind="list",
   tags=["money","systems"]),
 dict(id="T10", pillar="WORK CAPACITY", series="CAPABILITY STACK",
   hook="How to become hard to replace — without a new title.",
   sub="Career security is a stack, not a label.",
   beats=["Solve before escalation.", "Write clearly.", "Learn without a classroom.",
          "Keep promises.", "Make the people around you better."],
   quote="Career security is a stack, not a title.", keyword="HOW TO BE INDISPENSABLE AT WORK",
   cta="Rate yourself 1-5 on each. Fix the lowest.", accent="violet", kind="list",
   tags=["career","systems"]),
 dict(id="T11", pillar="MONEY SYSTEMS", series="THE $100 TEST",
   hook="You get $100. It must improve next month. Where does it go?",
   sub="Give each dollar one job.",
   beats=["Sleep.", "Skill.", "Training.", "A tool that saves time.",
          "Comment your allocation before you see everyone else's."],
   quote="Give each dollar one job.", keyword="BEST WAY TO SPEND 100 DOLLARS",
   numeral="$100", numeral_label="that must pay you back next month. Where does it go?",
   cta="Drop your allocation in the comments.", accent="volt", kind="stat",
   tags=["money","mindset"]),
 dict(id="T12", pillar="ENVIRONMENT ENGINEERING", series="PHONE AUDIT",
   hook="Your phone is either a tool or a slot machine. Which did you build?",
   sub="Your home screen is an environment.",
   beats=["Move feeds off the first screen.", "Put calendar and tasks where your thumb lands.",
          "Turn off alerts that create no action.", "Keep banking, notes and maps one tap away.",
          "Your home screen is an environment."],
   quote="Your home screen is an environment.", keyword="PHONE HOME SCREEN SETUP FOR FOCUS",
   cta="Rebuild your first screen tonight.", accent="violet", kind="sequence",
   tags=["declutter","time"]),
 dict(id="T13", pillar="RECOVERY PROTOCOL", series="RECOVERY IS A METRIC",
   hook="Recovery is a performance metric, not a reward.",
   sub="You do not rise to your goals. You fall to your recovery.",
   beats=["Same sleep and wake window.", "A hard stop on the screen.",
          "One real rest day, scheduled.", "Food and water on a timer.",
          "Track it or it did not happen."],
   quote="Track it or it did not happen.", keyword="RECOVERY ROUTINE FOR PERFORMANCE",
   cta="Schedule your rest day before the week starts.", accent="volt", kind="list",
   tags=["recovery","training"]),
 dict(id="T14", pillar="SOCIAL CAPITAL", series="THE 24-HOUR FOLLOW-UP",
   hook="Good conversation. Now the part almost everyone skips.",
   sub="Follow-up turns a moment into a relationship.",
   beats=["Within 24 hours, send one specific line from the talk.",
          "Add the promised link or intro.", "Do not write a paragraph.",
          "Set a reminder for the next natural touchpoint.",
          "Follow-up turns a moment into a relationship."],
   quote="Follow-up turns a moment into a relationship.", keyword="NETWORKING FOLLOW UP TEMPLATE",
   cta="Send one follow-up you have been sitting on.", accent="violet", kind="sequence",
   tags=["social","career"]),
 # ---- WEEK 3 — rebuild + decisions -----------------------------------------
 dict(id="T15", pillar="THE REBUILD", series="REBUILD ROADMAP",
   hook="You wake up at 22 with no network and no savings. First move?",
   sub="Spend the year becoming easy to recommend.",
   beats=["Build one month of breathing room.", "Choose one skill people already pay for.",
          "Get stronger and harder to exhaust.", "Publish proof of work.",
          "Become easy to recommend."],
   quote="Become easy to recommend.", keyword="HOW TO START OVER AT 22",
   cta="Which move would you make first?", accent="volt", kind="sequence",
   tags=["career","mindset"]),
 dict(id="T16", pillar="DECISION FILTER", series="THE FUTURE ME TEST",
   hook="Before the next yes, buy, quit or delay — run this test.",
   sub="Make decisions for the person who inherits them.",
   beats=["Will tomorrow-you thank you?", "Will one-year-you still care?",
          "Will five-year-you pay for it?", "If the answer worsens with time, change the move.",
          "Decide for the person who inherits it."],
   quote="Make decisions for the person who inherits them.", keyword="HOW TO MAKE BETTER DECISIONS",
   cta="Run it on the decision you are avoiding.", accent="violet", kind="list",
   tags=["mindset","systems"]),
 dict(id="T17", pillar="ESCAPE VELOCITY", series="FREEDOM MATH",
   hook="How many months could you breathe if income stopped tomorrow?",
   sub="That is runway, not net worth. Build the number that changes decisions.",
   beats=["Cash you can actually use.", "Essential monthly burn.", "Divide.",
          "That is runway, not net worth.", "Build the number that changes your decisions."],
   quote="Runway is the number that changes your decisions.", keyword="HOW TO CALCULATE YOUR RUNWAY",
   numeral="÷", numeral_label="usable cash over monthly burn. That is your runway.",
   cta="Do the math today. Write the number down.", accent="violet", kind="stat",
   tags=["money","career"]),
 dict(id="T18", pillar="RECEIPTS", series="FALSE SIGNALS",
   hook="Things that look like success but usually are not.",
   sub="Measure what compounds, not what photographs well.",
   beats=["A car payment that owns the month.", "A calendar packed with low-value work.",
          "A wardrobe funded by future income.", "A title with no transferable skill.",
          "Measure what compounds, not what photographs well."],
   quote="Measure what compounds, not what photographs well.", keyword="FAKE SUCCESS VS REAL SUCCESS",
   cta="Which signal have you been chasing?", accent="volt", kind="list",
   tags=["money","mindset"]),
 dict(id="T19", pillar="MONEY SYSTEMS", series="THE INVISIBLE SUBSCRIPTION AUDIT",
   hook="You are paying for more than apps. Most of it is invisible.",
   sub="Price the behavior, not just the subscription.",
   beats=["List recurring charges.", "Then recurring habits that create spending.",
          "Delivery. Convenience fees. Late fees. Top-ups.", "Price the behavior, not the app.",
          "Cancel one financial autopilot working against you."],
   quote="Price the behavior, not just the subscription.", keyword="HOW TO CUT SUBSCRIPTIONS AND SAVE",
   cta="Cancel one autopilot today.", accent="volt", kind="sequence",
   tags=["money","declutter"]),
 dict(id="T20", pillar="SYSTEM DESIGN", series="CUT LIST",
   hook="Your life gets easier when you stop doing these 5 things.",
   sub="What if the next upgrade is subtraction?",
   beats=["Stop answering everything immediately.", "Stop buying things to be seen.",
          "Stop keeping every option open.", "Stop negotiating with the plan.",
          "Pick one thing to remove for 7 days."],
   quote="The next upgrade is subtraction.", keyword="THINGS TO STOP DOING TO BE HAPPIER",
   cta="Pick one to cut for seven days.", accent="volt", kind="list",
   tags=["mindset","declutter"]),
 dict(id="T21", pillar="CAREER SIGNALS", series="SKILL STACK",
   hook="You do not need to be elite at one thing if the stack is rare.",
   sub="Build a combination that is hard to ignore.",
   beats=["Write.", "Sell.", "Use new tools quickly.", "Speak clearly.", "Understand money."],
   quote="A rare stack beats a single talent.", keyword="MOST VALUABLE SKILLS TO LEARN",
   cta="Which one is your weakest? Start there.", accent="violet", kind="list",
   tags=["career","skills" if False else "systems"]),
 # ---- WEEK 4 — receipts + presence -----------------------------------------
 dict(id="T22", pillar="168 HOURS", series="168 HOURS",
   hook="168 hours a week. Most of us can only account for 90.",
   sub="The calendar keeps receipts. Read last week before you plan next.",
   beats=["Sleep is a third of it.", "Work takes its slice.", "Then the 90 nobody tracks.",
          "Find the ten you would take back.", "Put one reclaimed hour on the calendar."],
   quote="168 hours a week. Where do yours go?", keyword="WHERE DOES MY TIME GO",
   numeral="168", numeral_label="hours a week. Where do yours actually go?",
   cta="Reclaim one hour. Schedule it now.", accent="violet", kind="stat",
   tags=["time","systems"]),
 dict(id="T23", pillar="ONE-WAY DOORS", series="COST REVEAL",
   hook="The most expensive habit nobody prices: waiting.",
   sub="Delay compounds too.",
   beats=["Waiting to apply.", "Waiting to invest.", "Waiting to leave.",
          "Waiting to start.", "Delay compounds too."],
   quote="Delay compounds too.", keyword="COST OF WAITING TOO LONG",
   cta="What have you been waiting on? Start it.", accent="volt", kind="list",
   tags=["mindset","money"]),
 dict(id="T24", pillar="PURCHASE LAB", series="BUY ONCE",
   hook="Cheap gets expensive when you use it every day.",
   sub="Buy once where it touches your body and your work.",
   beats=["Sleep surface.", "Shoes.", "Office chair.", "Luggage.", "Daily-use tech."],
   quote="Cheap gets expensive when you use it every day.", keyword="BUY IT FOR LIFE ESSENTIALS",
   cta="Which one are you overdue to upgrade?", accent="violet", kind="list",
   tags=["money","declutter"]),
 dict(id="T25", pillar="THE AUDIT", series="CALENDAR AUDIT",
   hook="Your calendar is a better personality test than your bio.",
   sub="Do not tell me your priorities. Show me last week.",
   beats=["Where did the evenings go?", "Who got your best hours?",
          "What moved forward?", "What kept getting moved?", "The calendar keeps receipts."],
   quote="Your calendar is your portfolio.", keyword="WHAT YOUR CALENDAR SAYS ABOUT YOU",
   cta="Open last week. What does it confess?", accent="volt", kind="list",
   tags=["time","mindset"]),
 dict(id="T26", pillar="MONEY SYSTEMS", series="PARALLEL STORY",
   hook="Two people get the same $1,000. Same money, different year.",
   sub="Same money. Different sequence.",
   beats=["Person A upgrades what can be seen.", "Person B buys breathing room.",
          "Then a tool or a skill.", "Then an asset.", "Same money. Different sequence."],
   quote="Same money. Different sequence.", keyword="SMART WAYS TO USE 1000 DOLLARS",
   numeral="$1K", numeral_label="two people, same money, completely different year.",
   cta="Which sequence are you running?", accent="violet", kind="stat",
   tags=["money","mindset"]),
 dict(id="T27", pillar="SOCIAL CAPITAL", series="PRESENCE AUDIT",
   hook="People notice these before they notice your clothes.",
   sub="Your outfit is not the first signal.",
   beats=["Posture.", "Voice.", "Grooming.", "Eye contact.",
          "Whether your attention is actually in the room."],
   quote="Presence is the first thing people read.", keyword="HOW TO MAKE A GOOD IMPRESSION",
   cta="Which one will you fix this week?", accent="volt", kind="list",
   tags=["social","mindset"]),
 dict(id="T28", pillar="FRICTION FILE", series="THE 20-MINUTE LIFE UPGRADE",
   hook="You have 20 minutes. Use them where the return lasts.",
   sub="Small friction removed today pays every day after.",
   beats=["Cancel one dead subscription.", "Book the appointment.", "Clear the desk.",
          "Move money automatically.", "Send the message you keep postponing."],
   quote="Twenty minutes on the right friction pays for months.", keyword="QUICK PRODUCTIVITY WINS",
   cta="Set a 20-minute timer. Pick one.", accent="volt", kind="list",
   tags=["time","systems"]),
 # ---- WEEK 5 — the boring edge ---------------------------------------------
 dict(id="T29", pillar="BORING EDGE", series="BORING EDGE",
   hook="What successful people make boring.",
   sub="The goal is to make the right move unsurprising.",
   beats=["Saving.", "Training.", "Following up.", "Sleeping.",
          "Make the right move unsurprising."],
   quote="Make the right move unsurprising.", keyword="BORING HABITS THAT BUILD SUCCESS",
   cta="Which habit needs to get boring for you?", accent="violet", kind="list",
   tags=["mindset","systems"]),
 dict(id="T30", pillar="PURCHASE LAB", series="THE DO-NOT-BUY-IT-YET CHECKLIST",
   hook="Checkout can wait 60 seconds. Run the first check.",
   sub="If the answers are weak, leave the tab open.",
   beats=["Will you use it 50 times?", "What is the cost per use?",
          "Are you buying the logo or the function?", "Would you still buy it without financing?",
          "If the answers are weak, leave the tab open."],
   quote="If the answers are weak, leave the tab open.", keyword="HOW TO STOP IMPULSE BUYING",
   cta="Save this before your next cart.", accent="volt", kind="list",
   tags=["money","mindset"]),
 dict(id="T31", pillar="RECOVERY PROTOCOL", series="THE ENERGY AUDIT",
   hook="Track your energy for 5 days. The pattern is louder than motivation.",
   sub="Design the day around your real peaks.",
   beats=["Note energy every two hours.", "Mark the true peak and the crash.",
          "Guard the peak for your hardest work.", "Protect the crash with recovery.",
          "Stop scheduling against your own biology."],
   quote="The pattern is louder than motivation.", keyword="HOW TO MANAGE YOUR ENERGY",
   cta="Start the five-day energy log today.", accent="violet", kind="sequence",
   tags=["recovery","time"]),
 dict(id="T32", pillar="ESCAPE VELOCITY", series="CAREER MAP",
   hook="Which skill could move your income without changing your whole life?",
   sub="Map skill to income before you burn a year.",
   beats=["Write your current skill stack.", "Mark what employers already pay for.",
          "Find the one adjacent skill that unlocks more.", "Build proof, not just a plan.",
          "Move the income lever you already have."],
   quote="Move the income lever you already have.", keyword="HIGH INCOME SKILLS TO LEARN",
   cta="Name your one adjacent skill.", accent="violet", kind="sequence",
   tags=["career","money"]),
 dict(id="T33", pillar="THE AUDIT", series="THE GOGETTR SCORECARD",
   hook="How together is your life, actually? Score it.",
   sub="Lowest score gets the next 30 days.",
   beats=["Money / 10.", "Work / 10.", "Training / 10.", "Recovery / 10.",
          "Lowest score gets the next 30 days."],
   quote="Lowest score gets the next 30 days.", keyword="LIFE SCORECARD SELF ASSESSMENT",
   cta="Post your lowest category below.", accent="volt", kind="list",
   tags=["systems","mindset"]),
 dict(id="T34", pillar="SOCIAL CAPITAL", series="REPUTATION LOOP",
   hook="Your reputation is compounding while you are not in the room.",
   sub="Reputation is the meeting you do not attend.",
   beats=["On time or late.", "Prepared or improvising.", "Keeps word or needs reminders.",
          "Useful or self-promotional.", "Reputation is the meeting you do not attend."],
   quote="Reputation is the meeting you do not attend.", keyword="HOW TO BUILD A GOOD REPUTATION",
   cta="What do they say after you leave?", accent="violet", kind="list",
   tags=["social","career"]),
 dict(id="T35", pillar="ENVIRONMENT ENGINEERING", series="THE 10% BETTER ROOM",
   hook="Do not redo the room. Fix the most annoying 10%.",
   sub="Choose the highest-friction corner and end it.",
   beats=["Find the corner you avoid.", "Name the one friction.", "Fix only that.",
          "Notice how the whole room lifts.", "Repeat next week, one corner at a time."],
   quote="Fix the most annoying 10%.", keyword="SMALL HOME UPGRADES THAT MATTER",
   cta="Which corner is your 10%?", accent="volt", kind="sequence",
   tags=["declutter","systems"]),
 # ---- WEEK 6 — signals + transfers -----------------------------------------
 dict(id="T36", pillar="CAREER SIGNALS", series="CAREER SIGNALS",
   hook="What your future employer cares about more than your GPA.",
   sub="Build evidence, not just credentials.",
   beats=["Can you explain clearly?", "Can you solve without being chased?",
          "Can people rely on your word?", "Can you show finished work?",
          "Build evidence, not just credentials."],
   quote="Build evidence, not just credentials.", keyword="WHAT EMPLOYERS ACTUALLY WANT",
   cta="Which proof are you missing?", accent="violet", kind="list",
   tags=["career","skills" if False else "mindset"]),
 dict(id="T37", pillar="PURCHASE LAB", series="THE WOULD-I-STILL-WANT-THIS RULE",
   hook="One question removes half your impulse buys.",
   sub="Strip the hype and ask again.",
   beats=["Remove the app that showed you.", "Remove your friends seeing it.",
          "Remove the logo.", "Remove launch-day hype.", "Still want it?"],
   quote="Strip the hype and ask again.", keyword="QUESTIONS BEFORE YOU BUY",
   cta="Try it on your open cart right now.", accent="volt", kind="list",
   tags=["money","mindset"]),
 dict(id="T38", pillar="RECOVERY PROTOCOL", series="SAVE CARD",
   hook="Save this for the next overwhelmed day. Do it in this order.",
   sub="Do not rebuild the system while you are inside the fire.",
   beats=["Write every open loop.", "Circle what matters today.",
          "Delete what has no consequence.", "Start the task you avoid most.",
          "Do not rebuild the system inside the fire."],
   quote="Do not rebuild the system while you are inside the fire.", keyword="WHAT TO DO WHEN OVERWHELMED",
   cta="Save this before you need it.", accent="volt", kind="sequence",
   tags=["recovery","mindset"]),
 dict(id="T39", pillar="BORING EDGE", series="AGE SHIFT",
   hook="Things that become valuable fast after 25.",
   sub="The boring things stop being boring.",
   beats=["Sleep.", "Good credit.", "Cooking.", "Real friendships.",
          "A body that still works without negotiation."],
   quote="The boring things stop being boring after 25.", keyword="THINGS THAT MATTER MORE AFTER 25",
   cta="Which one are you glad you started early?", accent="violet", kind="list",
   tags=["mindset","recovery"]),
 dict(id="T40", pillar="ENVIRONMENT ENGINEERING", series="THE DEFAULT GROCERY 12",
   hook="Keep 12 groceries that can always make something.",
   sub="Build your 12 once. Never stare at an empty fridge again.",
   beats=["Eggs and oats.", "Rice and beans.", "Frozen veg and fruit.",
          "A protein you trust.", "One sauce that saves any of it."],
   quote="Build your 12 once.", keyword="STAPLE GROCERY LIST FOR ADULTS",
   cta="What is on your default 12?", accent="volt", kind="list",
   tags=["systems","declutter"]),
 dict(id="T41", pillar="SYSTEM DESIGN", series="HABIT TRANSFER",
   hook="Steal one operating habit from each kind of high performer.",
   sub="You do not need their life. Take their habit.",
   beats=["Athlete: repetition.", "Salesperson: follow-up.", "Investor: patience.",
          "Founder: ownership.", "Creator: shipping."],
   quote="You do not need their life. Take their habit.", keyword="HABITS OF HIGH PERFORMERS",
   cta="Which habit do you steal first?", accent="violet", kind="list",
   tags=["mindset","systems"]),
 dict(id="T42", pillar="MINI CHALLENGES", series="THE 3-DAY NO-DELIVERY TEST",
   hook="Three days, no delivery apps. Notice what the convenience was solving.",
   sub="Test the friction, not your morality.",
   beats=["Delete the apps for 72 hours.", "Cook or walk to it.",
          "Notice the real cost you were paying.", "Keep the money you did not spend.",
          "Decide what stays deleted."],
   quote="Test the friction, not your morality.", keyword="NO SPEND CHALLENGE IDEAS",
   cta="Start the 3-day test today.", accent="volt", kind="challenge",
   tags=["challenge","money"]),
 # ---- WEEK 7 — inputs vs output --------------------------------------------
 dict(id="T43", pillar="THE AUDIT", series="SELF-HELP AUDIT",
   hook="You might be consuming self-improvement, not doing it.",
   sub="Count implementations, not inputs.",
   beats=["Saved posts.", "Unfinished books.", "Courses with no output.",
          "Podcasts replacing practice.", "Count implementations, not inputs."],
   quote="Count implementations, not inputs.", keyword="STOP CONSUMING START DOING",
   cta="What is one input you will finally apply?", accent="volt", kind="list",
   tags=["mindset","systems"]),
 dict(id="T44", pillar="MONEY SYSTEMS", series="BUDGET LADDER",
   hook="Same goal. Three budgets. Very different moves.",
   sub="Do not spread it across ten weak upgrades.",
   beats=["$20: remove one small friction.", "$200: upgrade a repeated process.",
          "$2,000: buy time, capability or runway.", "Give each dollar one job.",
          "One strong upgrade beats ten weak ones."],
   quote="Give each dollar one job.", keyword="HOW TO PRIORITIZE SPENDING",
   numeral="3", numeral_label="budgets, one goal. $20, $200, $2,000 — where do they go?",
   cta="Pick your tier and your one move.", accent="violet", kind="stat",
   tags=["money","systems"]),
 dict(id="T45", pillar="ENVIRONMENT ENGINEERING", series="THE EMERGENCY INFO NOTE",
   hook="Make one note with the info you would hate to search for under stress.",
   sub="Create it before you need it.",
   beats=["Emergency contacts.", "Insurance and policy numbers.", "Medications and doses.",
          "Roadside and account lines.", "Create it before you need it."],
   quote="Create it before you need it.", keyword="EMERGENCY INFORMATION CHECKLIST",
   cta="Build the note tonight.", accent="volt", kind="list",
   tags=["systems","declutter"]),
 dict(id="T46", pillar="SOCIAL CAPITAL", series="THE INTRODUCTION BANK",
   hook="Who could you connect without asking for anything back?",
   sub="Be useful before you need usefulness.",
   beats=["List 10 people and what they do.", "Draw lines where a match exists.",
          "Make one warm intro this week.", "Ask both sides first.",
          "Be useful before you need usefulness."],
   quote="Be useful before you need usefulness.", keyword="HOW TO NETWORK BY GIVING",
   cta="Make one intro this week.", accent="violet", kind="sequence",
   tags=["social","career"]),
 dict(id="T47", pillar="ONE-WAY DOORS", series="BRANCHING PATH",
   hook="Two versions of you wake up tomorrow. Which one gets the better year?",
   sub="Small forks become different lives.",
   beats=["Scroll or train.", "Impress or invest.", "Consume or build.",
          "Avoid or ask.", "Small forks become different lives."],
   quote="Small forks become different lives.", keyword="SMALL DECISIONS BIG IMPACT",
   cta="Which fork are you taking tomorrow?", accent="volt", kind="list",
   tags=["mindset","systems"]),
 dict(id="T48", pillar="MINI CHALLENGES", series="THE 5-DAY EARLY-ARRIVAL TEST",
   hook="Arrive five minutes early for five days. Track how different the day feels.",
   sub="Run the experiment. Let the result argue.",
   beats=["Five minutes early, five days.", "Notice the calmer start.",
          "Notice who reads it as respect.", "Notice the decisions you make unrushed.",
          "Keep what the data proves."],
   quote="Run the experiment. Let the result argue.", keyword="SMALL HABITS THAT CHANGE YOUR DAY",
   cta="Start the 5-day test tomorrow.", accent="violet", kind="challenge",
   tags=["challenge","time"]),
 dict(id="T49", pillar="SOCIAL CAPITAL", series="SOCIAL SIGNALS",
   hook="Things that quietly make you look competent.",
   sub="People read competence before they read credentials.",
   beats=["Arrive early.", "Take notes.", "Remember names.", "Answer the actual question.",
          "Follow up when you said you would."],
   quote="People read competence before they read credentials.", keyword="HOW TO APPEAR MORE COMPETENT",
   cta="Which one will you do today?", accent="volt", kind="list",
   tags=["social","career"]),
 # ---- WEEK 8 — small systems + finale --------------------------------------
 dict(id="T50", pillar="ENVIRONMENT ENGINEERING", series="THE PAPERWORK DROP ZONE",
   hook="Mail has two jobs: act or archive. Give both a place.",
   sub="Stop moving paper around the house.",
   beats=["One tray to ACT.", "One tray to FILE.", "Nothing lands anywhere else.",
          "Clear the ACT tray weekly.", "Stop moving paper around the house."],
   quote="Stop moving paper around the house.", keyword="HOW TO ORGANIZE PAPERWORK AT HOME",
   cta="Set up two trays today.", accent="volt", kind="sequence",
   tags=["declutter","systems"]),
 dict(id="T51", pillar="MINI CHALLENGES", series="THE ONE-WEEK NO-MULTITASK MEAL",
   hook="For seven meals, eat without a screen. Notice the pace.",
   sub="Seven meals, not forever.",
   beats=["No phone at the table.", "No show in the background.", "Just the meal.",
          "Notice how much less you need after.", "Seven meals, not forever."],
   quote="Seven meals, not forever.", keyword="MINDFUL EATING CHALLENGE",
   cta="Start at your next meal.", accent="violet", kind="challenge",
   tags=["challenge","recovery"]),
 dict(id="T52", pillar="BORING EDGE", series="THE UNSURPRISING MOVE",
   hook="Consistency is not intensity. It is making the right move unsurprising.",
   sub="Boring on the outside, compounding underneath.",
   beats=["Same time.", "Same trigger.", "Same small dose.",
          "No decision required.", "Boring on the outside, compounding underneath."],
   quote="Discipline is just a decision you already made.", keyword="HOW TO STAY CONSISTENT",
   cta="Which move will you make automatic?", accent="volt", kind="list",
   tags=["mindset","systems"]),
 dict(id="T53", pillar="ENVIRONMENT ENGINEERING", series="THE WEEKLY REFILL LIST",
   hook="Refill the same five things on the same day every week.",
   sub="Maintenance gets easier when it has a day.",
   beats=["Water and drinks.", "Meds and vitamins.", "Snacks and fuel.",
          "Gas or charge.", "The five essentials you always run out of."],
   quote="Maintenance gets easier when it has a day.", keyword="WEEKLY RESET CHECKLIST",
   cta="Pick your refill day.", accent="volt", kind="list",
   tags=["systems","declutter"]),
 dict(id="T54", pillar="MINI CHALLENGES", series="THE 5-NIGHT TOMORROW-NOTE",
   hook="For five nights, leave one sentence telling tomorrow where to start.",
   sub="Make morning inherit clarity.",
   beats=["One sentence before bed.", "The single first task.", "No list, no essay.",
          "Wake into a decision already made.", "Make morning inherit clarity."],
   quote="Make morning inherit clarity.", keyword="NIGHT ROUTINE FOR A PRODUCTIVE MORNING",
   cta="Write tonight's sentence now.", accent="violet", kind="challenge",
   tags=["challenge","time"]),
 dict(id="T55", pillar="SOCIAL CAPITAL", series="THE BETTER SECOND QUESTION",
   hook="Most conversations die on the second question. Here is the fix.",
   sub="Trade the reflex question for a real one.",
   beats=["Skip 'so what do you do'.", "Ask about the part they lit up on.",
          "Follow the energy, not the script.", "Let silence do some work.",
          "Curiosity is the whole skill."],
   quote="Curiosity is the whole skill.", keyword="HOW TO HAVE BETTER CONVERSATIONS",
   cta="Try it in your next conversation.", accent="volt", kind="sequence",
   tags=["social","mindset"]),
 dict(id="T56", pillar="SYSTEM DESIGN", series="BUILD THE MACHINE — RECAP",
   hook="You do not rise to your goals. You fall to your systems.",
   sub="Eight weeks in one line: build the machine, skip the mood.",
   beats=["Fewer decisions.", "Automatic money.", "Scheduled recovery.",
          "Proof of work.", "Track it or it did not happen."],
   quote="Build the machine. Skip the mood.", keyword="HOW TO BUILD LIFE SYSTEMS THAT LAST",
   cta="Save the whole series. Start the machine.", accent="volt", kind="list",
   tags=["systems","core"]),
]

assert len(THEMES) == 56, len(THEMES)
